docker start ca.org1.example.com &
docker start ca.org2.example.com &
docker start ipfs.cluster.peer1 &
docker start ipfs.cluster.peer2 &
docker start zookeeper0 &
docker start zookeeper1 &
docker start zookeeper2 &
docker start couchdb1 &
docker start couchdb2 &
docker start couchdb3 &
docker start couchdb4 &
docker start browser.db &
