docker stop ca.org1.example.com &
docker stop ca.org2.example.com &
docker stop ipfs.cluster.peer1 &
docker stop ipfs.cluster.peer2 &
docker stop zookeeper0 &
docker stop zookeeper1 &
docker stop zookeeper2 &
docker stop couchdb1 &
docker stop couchdb2 &
docker stop couchdb3 &
docker stop couchdb4 &
docker stop browser.db &
